(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const app=$('#app');
const state={owner:[],reseller:[],source:'owner',filtered:[],product:null,invoice:null,search:''};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
async function api(a,body=null,query={}){
 const u=new URL('/api/xo',location.origin);u.searchParams.set('a',a);Object.entries(query).forEach(([k,v])=>{if(v!==''&&v!=null)u.searchParams.set(k,v)});
 const opt=body===null?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)};
 const r=await fetch(u,opt);let j;try{j=await r.json()}catch{throw new Error('Server mengirim respons tidak valid.')};if(!j.ok)throw new Error(j.error||'Request gagal');return j.data;
}
function invoices(){try{return JSON.parse(localStorage.getItem('vanzshop_xo_invoices')||'[]')}catch{return[]}}
function saveInvoice(inv){const arr=invoices().filter(x=>x.transaction_id!==inv.transaction_id);arr.unshift(inv);localStorage.setItem('vanzshop_xo_invoices',JSON.stringify(arr.slice(0,30)))}
function toast(msg,bad=false){let b=$('.toasts');if(!b){b=document.createElement('div');b.className='toasts';document.body.appendChild(b)}const t=document.createElement('div');t.className='toast'+(bad?' bad':'');t.textContent=msg;b.appendChild(t);setTimeout(()=>t.remove(),4500)}
function shell(content,active='catalog'){app.innerHTML=`<div class="shop"><header class="topbar"><div class="wrap"><a class="brand" href="#/"><span class="brand-mark">V</span><span class="brand-name">VanzShop.com</span></a><nav class="nav"><a href="#/" ${active==='catalog'?'aria-current="page"':''}>Katalog</a><a href="#/pesanan" ${active==='orders'?'aria-current="page"':''}>Pesanan</a></nav></div></header>${content}<footer class="footer"><div class="wrap"><b>VanzShop.com</b><p class="footer-note">Live catalog & transaksi terintegrasi langsung dengan Xoftware API.</p></div></footer></div>`}
function productName(p){return p.title||p.name||'Produk'}
function productCode(p){return p.code||''}
function productPrice(p){if(p.price!=null&&Number(p.price)>0)return Number(p.price);const vs=Array.isArray(p.variations)?p.variations:[];const vals=vs.map(v=>Number(v.price)||0).filter(n=>n>0);return vals.length?Math.min(...vals):0}
function productStock(p){if(p.stock!=null)return Number(p.stock);const vs=Array.isArray(p.variations)?p.variations:[];return vs.length?vs.reduce((n,v)=>n+Number(v.stock_count??v.stock??0),0):null}
function productImage(p){return p.thumbnail||p.image||p.img||''}
function currentProducts(){return state.source==='reseller'?state.reseller:state.owner}
async function load(){
 shell(`<section class="xhero"><div class="wrap"><div class="xhero-grid"><div><div class="eyebrow">LIVE CATALOG · XOFTWARE API</div><h1>Produk langsung <span>dari VanzShop & Xoftware.</span></h1><p>VanzShop membaca katalog secara live dari API. Tidak ada database produk lokal.</p><div class="xstats"><div class="xstat"><b id="sOwner">—</b><span>produk toko</span></div><div class="xstat"><b id="sReseller">—</b><span>Star Seller</span></div><div class="xstat"><b>0 DB</b><span>tanpa database lokal</span></div></div></div><div class="xpanel"><b>⚡ Server-side API proxy</b><p class="hint" style="margin-top:8px">API key Xoftware hanya berada di environment Vercel. Browser tidak menerima API key.</p><hr class="rule"><div id="apiWarn" class="xnotice">Memuat status API…</div></div></div></div></section><section class="xcatalog"><div class="wrap"><div class="xtoolbar"><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" id="tabOwner">Produk Toko</button><button class="btn" id="tabReseller">Star Seller</button></div><div style="display:flex;gap:8px;flex:1;min-width:260px"><input id="search" class="input" placeholder="Cari nama produk atau SKU…"><button class="btn" id="refresh">Refresh</button></div></div><div id="grid" class="xgrid"><div class="xloading"><span class="xspin"></span>Memuat katalog…</div></div></div></section>`,'catalog');
 $('#refresh').onclick=()=>load();$('#search').oninput=e=>{state.search=e.target.value.toLowerCase();renderGrid()};$('#tabOwner').onclick=()=>{state.source='owner';state.search='';$('#search').value='';syncTabs();renderGrid()};$('#tabReseller').onclick=()=>{state.source='reseller';state.search='';$('#search').value='';syncTabs();renderGrid()};
 try{const d=await api('init');state.owner=Array.isArray(d.owner_products)?d.owner_products:[];state.reseller=Array.isArray(d.reseller_products)?d.reseller_products:[];$('#sOwner').textContent=state.owner.length;$('#sReseller').textContent=state.reseller.length;$('#apiWarn').innerHTML=d.warnings?.length?d.warnings.map(esc).join('<br>'):'Semua catalog yang diaktifkan berhasil dibaca.';syncTabs();renderGrid()}
 catch(e){$('#apiWarn').textContent=e.message;$('#grid').innerHTML=`<div class="xempty"><b>Gagal memuat API</b><p style="margin-top:8px">${esc(e.message)}</p></div>`}
}
function syncTabs(){const a=$('#tabOwner'),b=$('#tabReseller');if(a){a.classList.toggle('btn-primary',state.source==='owner');b.classList.toggle('btn-primary',state.source==='reseller')}}
function renderGrid(){const q=state.search,all=currentProducts();state.filtered=all.filter(p=>!q||productName(p).toLowerCase().includes(q)||productCode(p).toLowerCase().includes(q)||String(p.provider_name||'').toLowerCase().includes(q));const g=$('#grid');if(!g)return;if(!state.filtered.length){g.innerHTML='<div class="xempty">Produk tidak ditemukan.</div>';return}g.innerHTML=state.filtered.map((p,i)=>`<article class="xcard"><div class="xthumb">${productImage(p)?`<img src="${esc(productImage(p))}" alt="">`:''}</div><div class="xbody"><div class="eyebrow">${esc(p.source==='reseller'?'STAR SELLER':productCode(p))}</div><h3>${esc(productName(p))}</h3><p class="desc">${esc(p.description||'Produk digital tersedia otomatis.')}</p>${p.provider_name?`<p class="hint">Provider: ${esc(p.provider_name)}</p>`:''}<div class="xprice"><div><small>Mulai dari</small><strong>${rupiah(productPrice(p))}</strong></div><button class="btn btn-primary btn-sm" data-open="${i}">Detail</button></div></div></article>`).join('');$$('[data-open]').forEach(b=>b.onclick=()=>openProduct(state.filtered[+b.dataset.open]))}
function openProduct(p){state.product=p;if(p.source==='reseller')return openResellerProduct(p);return openOwnerProduct(p)}
function variationChoices(p,source){const vars=Array.isArray(p.variations)?p.variations:[];if(!vars.length)return '';return `<h3 style="margin-top:24px">Pilih variasi</h3><div class="xvariant">${vars.map((v,i)=>`<label><span><input type="radio" name="variant" value="${i}" ${i===0?'checked':''}> <b>${esc(v.title||v.name||('Variasi '+(i+1)))}</b></span><b>${rupiah(v.price)}</b></label>`).join('')}</div>`}
function openOwnerProduct(p){const vars=Array.isArray(p.variations)?p.variations:[];app.innerHTML=`<div class="shop"><header class="topbar"><div class="wrap"><a class="brand" href="#/">VanzShop.com</a><nav class="nav"><a href="#/">Katalog</a><a href="#/pesanan">Pesanan</a></nav></div></header><section class="xdetail"><div class="wrap"><button class="btn btn-ghost" id="back">← Kembali</button><div class="xdetail-grid" style="margin-top:18px"><div class="xpanel"><div class="eyebrow">OWNER CATALOG · ${esc(productCode(p))}</div><h1 style="font-family:var(--f-display);font-size:clamp(32px,4vw,50px);margin-top:8px">${esc(productName(p))}</h1><p class="hint" style="margin-top:12px">${esc(p.description||'')}</p>${variationChoices(p,'owner')}</div><div class="xpanel"><form id="buy" class="xform"><div class="field"><label>WhatsApp / Telegram ID</label><input class="input" name="sender" required placeholder="62812xxxx / Telegram ID"></div><div class="field"><label>Nama</label><input class="input" name="name" required placeholder="Nama Anda"></div><div class="field"><label>Jumlah</label><input class="input" name="qty" type="number" min="1" max="999999" value="1" required></div><div class="field"><label>Metode</label><select class="select" name="method"><option value="qris">QRIS — Xoftware</option><option value="balance">Saldo Xoftware</option></select></div><div class="xnotice">Owner Order API: register → checkout → status.</div><button class="btn btn-primary btn-lg btn-block" type="submit">Lanjutkan Pembelian</button></form></div></div></div></section></div>`;$('#back').onclick=()=>load();$('#buy').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),sender=String(fd.get('sender')).trim(),name=String(fd.get('name')).trim(),qty=Math.max(1,Number(fd.get('qty'))||1),method=String(fd.get('method'));let code=p.code;if(vars.length){const v=vars[Number($('input[name="variant"]:checked').value)];code=v.code||p.code}const btn=$('button[type=submit]',e.currentTarget);btn.disabled=true;btn.textContent='Memproses…';try{try{await api('register',{sender,name})}catch(regErr){if(!/already|registered|terdaftar|exist|duplicate/i.test(regErr.message))throw regErr}const r=method==='balance'?await api('order_balance',{sender,code,quantity:qty}):await api('order_qris',{sender,code,quantity:qty});const d=r.data||r,tx=String(d.transaction_id??d.reff_id??d.id??'');if(!tx)throw new Error('Xoftware tidak mengembalikan transaction_id.');const inv={transaction_id:tx,sender,code,product_name:productName(p),quantity:qty,method,total:d.total_to_pay??d.total_price??d.amount??productPrice(p)*qty,qr_string:d.qr_string||'',link:d.link||'',status:d.status||'pending',accounts:d.accounts||[],created_at:Date.now(),source:'owner'};state.invoice=inv;saveInvoice(inv);location.hash='#/invoice/'+encodeURIComponent(tx)}catch(err){toast(err.message,true);btn.disabled=false;btn.textContent='Lanjutkan Pembelian'}}}
function openResellerProduct(p){const vars=Array.isArray(p.variations)?p.variations:[];const selectedStock=Number(p.id);app.innerHTML=`<div class="shop"><header class="topbar"><div class="wrap"><a class="brand" href="#/">VanzShop.com</a><nav class="nav"><a href="#/">Katalog</a><a href="#/pesanan">Pesanan</a></nav></div></header><section class="xdetail"><div class="wrap"><button class="btn btn-ghost" id="back">← Kembali</button><div class="xdetail-grid" style="margin-top:18px"><div class="xpanel"><div class="eyebrow">STAR SELLER · ${esc(productCode(p))}</div><h1 style="font-family:var(--f-display);font-size:clamp(32px,4vw,50px);margin-top:8px">${esc(productName(p))}</h1><p class="hint" style="margin-top:12px">${esc(p.description||'')}</p><p class="hint" style="margin-top:8px">Provider: ${esc(p.provider_name||'Star Seller')}</p>${variationChoices(p,'reseller')}</div><div class="xpanel"><form id="buyRes" class="xform"><div class="xnotice"><b>Reseller H2H</b><br>Pembelian memotong <code>reseller_saldo</code> bot Xoftware dan akun dikirim langsung di response order.</div><div class="field"><label>Jumlah</label><input class="input" name="qty" type="number" min="1" max="999999" value="1" required></div><div class="field"><label>Konfirmasi</label><input type="checkbox" name="confirm" required> Saya paham transaksi ini memakai saldo reseller.</div><button class="btn btn-primary btn-lg btn-block" type="submit">Order dari Star Seller</button></form><div id="resResult" style="margin-top:18px"></div></div></div></div></section></div>`;$('#back').onclick=()=>load();$('#buyRes').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const qty=Math.max(1,Number(fd.get('qty'))||1);let variation_id='';if(vars.length){const v=vars[Number($('input[name="variant"]:checked').value)];variation_id=v.id??v.variation_id??''}const btn=$('button[type=submit]',e.currentTarget);btn.disabled=true;btn.textContent='Order…';try{const d=await api('reseller_order',{stock_id:selectedStock,variation_id,quantity:qty});const x=d.data||d;$('#resResult').innerHTML=`<div class="xnotice ok"><b>Order berhasil</b><br>Reff: ${esc(x.reff_id||x.id||'-')}<br>Total: ${rupiah(x.total_price??0)}</div>${Array.isArray(x.accounts)?`<div style="margin-top:12px"><h3>Akun diterima</h3>${x.accounts.map(a=>`<div class="xaccount"><pre>${esc(typeof a==='string'?a:JSON.stringify(a,null,2))}</pre></div>`).join('')}</div>`:''}`;btn.disabled=false;btn.textContent='Order dari Star Seller'}catch(err){toast(err.message,true);btn.disabled=false;btn.textContent='Order dari Star Seller'}}}
let pollTimer=null;
function invoicesPage(){const list=invoices();shell(`<section class="xinvoice"><div class="wrap"><div class="xpanel"><div class="eyebrow">LOCAL HISTORY</div><h1 style="font-family:var(--f-display);font-size:38px;margin-top:6px">Pesanan</h1><p class="hint" style="margin-top:8px">Riwayat owner-order hanya disimpan di browser. Data reseller tidak disimpan server-side.</p><div style="margin-top:20px">${list.length?list.map(x=>`<div class="xaccount" style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><b>${esc(x.product_name)}</b><div class="hint">${esc(x.transaction_id)} · ${new Date(x.created_at).toLocaleString('id-ID')}</div></div><a class="btn btn-sm" href="#/invoice/${encodeURIComponent(x.transaction_id)}">Buka</a></div>`).join(''):'<div class="xempty">Belum ada pesanan.</div>'}</div></div></div></section>`,'orders')}
async function invoice(tx){const inv=invoices().find(x=>x.transaction_id===tx);if(!inv){shell('<section class="xinvoice"><div class="wrap"><div class="xempty">Invoice tidak ditemukan di perangkat ini.</div></div></section>','orders');return}renderInvoice(inv)}
function renderInvoice(inv){if(pollTimer){clearInterval(pollTimer);pollTimer=null}shell(`<section class="xinvoice"><div class="wrap"><div class="xinvoice-grid"><div class="xpanel"><div class="eyebrow">TRANSACTION ID</div><h1 style="font-family:var(--f-display);font-size:32px;margin-top:8px">${esc(inv.transaction_id)}</h1><div id="status" style="margin-top:15px"></div><div id="result" style="margin-top:18px"></div></div><div class="xpanel"><h3>Pembayaran</h3><p class="hint" style="margin-top:6px">${esc(inv.product_name)} · x${inv.quantity}</p>${inv.qr_string?'<div class="xqr" id="qr"></div>':''}<div id="payInfo" class="xnotice" style="margin-top:12px"></div>${inv.link?`<a class="btn btn-primary btn-block" style="margin-top:10px" target="_blank" rel="noopener" href="${esc(inv.link)}">Buka halaman pembayaran</a>`:''}<button class="btn btn-block" id="check" style="margin-top:10px">Cek Status</button></div></div></div></section>`,'orders');if(inv.qr_string&&$('#qr'))new QRCode($('#qr'),{text:inv.qr_string,width:260,height:260});$('#check').onclick=()=>checkStatus(inv);checkStatus(inv);if(['pending','unpaid','unpaid'].includes(String(inv.status).toLowerCase()))pollTimer=setInterval(()=>checkStatus(inv),8000)}
async function checkStatus(inv){try{const d=await api('order_status',{transaction_id:inv.transaction_id});const x=d.data||d,s=String(x.status||'pending').toLowerCase();inv.status=s;inv.accounts=x.accounts||inv.accounts||[];inv.total=x.total??x.total_price??inv.total;saveInvoice(inv);const success=['success','paid'].includes(s),bad=['fail','failed'].includes(s);$('#status').innerHTML=`<div class="xnotice ${success?'ok':bad?'bad':''}"><b>${success?'Pembayaran berhasil':bad?'Pembayaran gagal':'Menunggu pembayaran'}</b><br><span>${esc(s.toUpperCase())}</span></div>`;$('#payInfo').textContent=success?`Total ${rupiah(inv.total)} · Produk sudah diterima.`:`Total ${rupiah(inv.total)} · status dicek otomatis.`;if(inv.accounts?.length){$('#result').innerHTML=`<h3>Produk / akun diterima</h3>${inv.accounts.map(a=>`<div class="xaccount"><pre>${esc(typeof a==='string'?a:JSON.stringify(a,null,2))}</pre></div>`).join('')}`;if(pollTimer){clearInterval(pollTimer);pollTimer=null}}}catch(e){$('#status').innerHTML=`<div class="xnotice bad">${esc(e.message)}</div>`}}
function router(){const h=location.hash||'#/';if(h.startsWith('#/invoice/'))return invoice(decodeURIComponent(h.slice(10)));if(h==='#/pesanan')return invoicesPage();return load()}
window.addEventListener('hashchange',router);router();
})();
