'use strict';
const assert = require('assert');
const fs = require('fs');
const js = fs.readFileSync(require('path').join(__dirname,'../assets/xshop.js'),'utf8');
const html = fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8');
const vercel = JSON.parse(fs.readFileSync(require('path').join(__dirname,'../vercel.json'),'utf8'));
assert.match(js,/const BUILD_ID = 'HARDMAX-v18-COMMERCE-SEO'/);
assert.match(js,/function activeRoute\(\)/);
assert.match(js,/p==='\/admin'/);
assert.match(js,/adminEndpointMap/);
assert.match(js,/adminBalanceOrder/);
assert.match(js,/adminVariations/);
assert.match(js,/adminEnvironment/);
assert.match(js,/diag_product/);
assert.match(html,/xshop\.js\?v=28/);
assert.equal(vercel.cleanUrls,true);
assert.ok(fs.existsSync(require('path').join(__dirname,'../admin.html')));
console.log('PASS frontend.test.js');

assert.match(js,/admin_login/);
assert.match(js,/vanz_admin_token/);
assert.match(js,/authorization/);

assert.match(js,/payment_create/);
assert.match(js,/payment_status/);
assert.match(js,/Sewa Pay/);

assert.match(js,/fulfillment_retry/);
assert.match(js,/Produk siap digunakan/);
assert.match(js,/function adminProductRecap\(/);
assert.match(js,/function optimizeProductImage\(/);
assert.match(js,/pm_product_media_set/);
assert.match(js,/STORE_BANNER_SECONDS=/);
assert.match(js,/data-theme-toggle/);
assert.match(js,/function bindGlobalSearch\(/);
assert.match(js,/function renderCart\(/);
assert.match(js,/function renderProfile\(/);
assert.match(js,/function bindAssistant\(/);
assert.match(js,/function syncPaymentOrder\(/);
assert.match(js,/GLOBAL REFERENCE SEARCH/);
assert.match(js,/ORDER CONTROL CENTER/);
assert.match(js,/vanzcat-launch/);
assert.match(js,/Pusat Premium Digital/);
assert.match(js,/VANZSHOP\.COM · OFFICIAL ECOSYSTEM/);
assert.match(js,/DQ2PsowpGt5FxhQDAS2sAz/);
assert.match(js,/Yang kamu dapat/);
const publicShell=js.slice(js.indexOf('function shell('),js.indexOf('function bindThemeToggle'));
assert.ok(!publicShell.includes('#/isi-saldo'),'topup must not appear in storefront navigation');
assert.ok(!publicShell.includes('#/akun'),'account registration must not appear in storefront navigation');
assert.ok(!publicShell.includes('href="#/admin"'),'admin dashboard must not be exposed in public navigation');
